version: '3.7'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - './docker/.env.db'
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data