apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.name }}
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.Service.port }}
      targetPort: {{ .Values.appPort }}
