---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.Storage.pv_name }}
spec:
  capacity:
    storage: {{ .Values.Storage.size }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: {{ .Values.Storage.driver }}
    volumeHandle: {{ .Values.Storage.volumeHandle }}

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.Storage.pvc_name }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.Storage.size }}