- name: Add deployers group
  group:
    name: deployers
    state: present

- name: Add docker group
  group:
    name: docker
    state: present

- name: Add docker_manager user
  user:
    name: docker_manager
    password: "{{ docker_manager_password }}"
    groups: [ 'docker','deployers' ]


- name: set ansible user key
  authorized_key:
    user: ansible
    key: "{{ item }}"
  with_file: keys/{{ ansible_key }}.pub

- name: set docker_manager user key
  authorized_key:
    user: docker_manager
    key: "{{ item }}"
  with_file: keys/{{ docker_key }}.pub
